
version: 2.1
jobs:
  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Dependencies
          command: yarn install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Authenticate
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            git config --global user.email $GITHUB_EMAIL
            git config --global user.name $GITHUB_USER
      - run:
          command: |
            npm run release:ci
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          context: availity-deploy
          filters:
            branches:
              only: master
